"""The declarative base, and the column decisions taken once here instead of per table."""

from __future__ import annotations

from datetime import datetime
from typing import Any, ClassVar, Final

from sqlalchemy import ARRAY, BigInteger, DateTime, MetaData, Text, Uuid, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from adrobot.domain.ids import (
    CampaignId,
    DraftId,
    KeitaroCampaignId,
    KeitaroStreamId,
    OfferId,
    PushAttemptId,
)

# Without this, autogenerated constraints come out unnamed and a later migration has no
# name to drop them by. `%(constraint_name)s` obliges every CheckConstraint to carry one.
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Every table in this service hangs on this one base and its one `MetaData`."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # The tracker's identifiers and ours keep the separation domain/ids.py gives them in
    # Python: `Mapped[OfferId]` cannot be written where `Mapped[KeitaroStreamId]` belongs.
    # Their width is the tracker's business, so bigint rather than a guess at its range.
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        CampaignId: Uuid(),
        DraftId: Uuid(),
        PushAttemptId: Uuid(),
        KeitaroCampaignId: BigInteger(),
        KeitaroStreamId: BigInteger(),
        OfferId: BigInteger(),
        # SQLAlchemy's defaults for these two are VARCHAR without a length and a naive
        # timestamp; the second silently drops the offset off a tracker timestamp.
        str: Text(),
        datetime: DateTime(timezone=True),
        dict[str, Any]: JSONB(),
        list[str]: ARRAY(Text()),
    }


class TimestampsMixin:
    """Row age, written by the database so a migration or a psql insert carries it too."""

    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    # Emitted by SQLAlchemy on an ORM update rather than by a trigger: a row changed from
    # psql keeps its old value.
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())
