repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: env -u VIRTUAL_ENV poetry -P backend run ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-check
        name: ruff check
        entry: env -u VIRTUAL_ENV poetry -P backend run ruff check
        language: system
        types_or: [python, pyi]
        require_serial: true
        
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
