/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List campaigns, newest first
         * @description Read one page. `after` is the `next_cursor` of the page before it, unread.
         */
        get: operations["list_campaigns_api_v1_campaigns_get"];
        put?: never;
        /**
         * Create a campaign with its two flows
         * @description Build the campaign part 1 describes, and report how far the tracker let us get.
         */
        post: operations["create_campaign_api_v1_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a campaign the tracker already has
         * @description Mirror an existing campaign and its flows, which is what part 2 opens.
         */
        post: operations["import_campaign_api_v1_campaigns_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/refetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read this campaign and its flows from the tracker again
         * @description FETCH STREAMS FROM KT. What the tracker no longer returns is kept and marked absent.
         */
        post: operations["refetch_campaign_api_v1_campaigns__campaign_id__refetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish a campaign whose flows were never built
         * @description Create whatever of the two flows the tracker does not have. Safe to press twice.
         */
        post: operations["repair_campaign_api_v1_campaigns__campaign_id__repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read this campaign's clicks today, by flow and by offer
         * @description Two reports behind one answer, cached for the whole process for forty-five seconds.
         *
         *     No 502 in the list above, and that is the endpoint's contract rather than an oversight:
         *     a report the tracker would not build comes back as `available: false` with a reason.
         */
        get: operations["read_campaign_stats_api_v1_campaigns__campaign_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one campaign's flows as the editor draws them
         * @description Draw the whole screen in one answer: the mirror, the live draft over it, the pins.
         */
        get: operations["read_streams_api_v1_campaigns__campaign_id__streams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/streams/{stream_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Throw this flow's staged edits away
         * @description CANCEL. The pins survive it, and so do the tracker's own unnormalised shares.
         */
        delete: operations["discard_draft_api_v1_campaigns__campaign_id__streams__stream_id__draft_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/streams/{stream_id}/draft/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stage add, remove and bring back on this flow
         * @description Apply a batch of edits. All or nothing: a refusal leaves the flow exactly as it was.
         */
        post: operations["edit_draft_api_v1_campaigns__campaign_id__streams__stream_id__draft_operations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/streams/{stream_id}/draft/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show what pressing PUSH would send, without sending it
         * @description Rehearse the push: `diff.desired` is the payload it would send, not a description.
         */
        get: operations["preview_draft_api_v1_campaigns__campaign_id__streams__stream_id__draft_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/streams/{stream_id}/draft/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write this flow's draft to the tracker
         * @description PUSH TO KT. A 409 carrying `conflict` means somebody edited the flow in Keitaro.
         */
        post: operations["push_draft_api_v1_campaigns__campaign_id__streams__stream_id__draft_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/streams/{stream_id}/offers/{offer_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Hold one row's share where it is
         * @description Pin a row. Deliberately moves no other share and lights no button — see the use case.
         */
        put: operations["pin_offer_api_v1_campaigns__campaign_id__streams__stream_id__offers__offer_id__pin_put"];
        post?: never;
        /**
         * Let one row back into the division
         * @description Release the pin if there is one. Silent when there is not: a second press is not an error.
         */
        delete: operations["unpin_offer_api_v1_campaigns__campaign_id__streams__stream_id__offers__offer_id__pin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the mirrored offer catalogue
         * @description No text is SHOW ALL OFFERS. An id prefix outranks a name that merely contains it.
         */
        get: operations["search_offers_api_v1_offers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/offers/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read the tracker's whole offer list again
         * @description `synced_at` is null when the tracker listed nothing: the copy was left alone.
         */
        post: operations["sync_offers_api_v1_offers_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Answer 200 for as long as the process can serve a request.
         *
         *     Dependency-free on purpose: a liveness probe that touches the database turns a slow
         *     query into a container restart loop.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Report whether this process is ready to take traffic.
         *
         *     At 1.6 it has nothing to ask: there is no database yet, and the tracker is not
         *     allowed to be part of this verdict. It answers 200 with an empty `checks` rather than
         *     inventing a component that cannot fail.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CampaignResponse
         * @description A campaign as this API answers for one.
         *
         *     `public_url` is a plain string and not an `HttpUrl`: it is built from a domain name the
         *     tracker gave us, and a response model that refused to serialise somebody else's data
         *     would turn a campaign that exists into a 500.
         */
        CampaignResponse: {
            /** Alias */
            alias: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Keitaro Campaign Id */
            keitaro_campaign_id: number;
            /** Name */
            name: string;
            /** Public Url */
            public_url?: string | null;
            /** Requested Country */
            requested_country?: string | null;
            /** Requested Offer Id */
            requested_offer_id?: number | null;
            /**
             * Setup Failure
             * @description Why this campaign's flows are missing, filled in by the call that has just tried to build them. A campaign read back later says `needs_attention` without it.
             */
            setup_failure?: string | null;
            setup_status: components["schemas"]["CampaignSetupStatus"];
            /** State */
            state: string;
            /** Synced At */
            synced_at?: string | null;
        };
        /**
         * CampaignSetupStatus
         * @description How far part 1 got with this campaign.
         *
         *     The tracker cannot answer it: the campaign exists there either way, and only a flow
         *     that was never created tells the two apart.
         * @enum {string}
         */
        CampaignSetupStatus: "ready" | "needs_attention";
        /**
         * CampaignStatsResponse
         * @description One campaign's numbers for one day, with everything needed to caption them.
         *
         *     A flow or an offer the report did not mention has no row at all, and that is deliberate:
         *     a zero written here would be this service inventing a measurement. The screen draws an
         *     empty cell, which is what "the tracker said nothing about this" looks like.
         */
        CampaignStatsResponse: {
            /**
             * Available
             * @description Whether these rows are the tracker's numbers at all. False is not an empty day: a campaign with no traffic is available with no rows.
             */
            available: boolean;
            /**
             * Day
             * Format: date
             * @description The tracker's day, not this service's.
             */
            day: string;
            /**
             * Offers
             * @default []
             */
            offers: components["schemas"]["OfferStatsResponse"][];
            /**
             * Read At
             * @description When the tracker answered, and null when it never has.
             */
            read_at?: string | null;
            /**
             * Stale
             * @description These are the last numbers that could be read, not today's latest.
             * @default false
             */
            stale: boolean;
            /**
             * Streams
             * @default []
             */
            streams: components["schemas"]["StreamStatsResponse"][];
            /**
             * Timezone
             * @description The IANA zone `day` was worked out in.
             */
            timezone: string;
            /**
             * Unavailable Reason
             * @description Why the last attempt failed, in words a buyer reads.
             */
            unavailable_reason?: string | null;
        };
        /**
         * CampaignsPageResponse
         * @description One page and the token that continues it, `null` meaning there is nothing after.
         */
        CampaignsPageResponse: {
            /** Campaigns */
            campaigns: components["schemas"]["CampaignResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ConflictingState
         * @description Two readings of one flow, side by side, in the same shape so they can be diffed.
         *
         *     Carried on the 409 a push answers when the flow has been edited in Keitaro meanwhile.
         *     A body that only said "conflict" would leave the screen with nothing to show and the
         *     person with nothing to decide between overwriting and discarding.
         */
        ConflictingState: {
            /** Push Would Write */
            push_would_write: components["schemas"]["OfferShare"][];
            /** Tracker Holds */
            tracker_holds: components["schemas"]["OfferShare"][];
        };
        /**
         * CreateCampaignRequest
         * @description Part 1's three fields.
         */
        CreateCampaignRequest: {
            /**
             * Country
             * @description ISO 3166-1 alpha-2. Flow 1 catches this country and sends it away.
             * @example MX
             */
            country: string;
            /**
             * Name
             * @description What the campaign is called in the tracker.
             */
            name: string;
            /**
             * Offer Id
             * @description The offer Flow 2 rotates, as the tracker numbers it.
             */
            offer_id: number;
        };
        /**
         * DraftDiffResponse
         * @description What the draft would change, for a person and for the tracker.
         *
         *     `desired` is the exact payload a push sends, not a description of one: it is the same
         *     tuple, rendered by the same function. That is what makes PREVIEW a rehearsal.
         */
        DraftDiffResponse: {
            /**
             * Added
             * @default []
             */
            added: number[];
            /**
             * Brought Back
             * @default []
             */
            brought_back: number[];
            /**
             * Desired
             * @default []
             */
            desired: components["schemas"]["OfferShare"][];
            /**
             * Removed
             * @default []
             */
            removed: number[];
            /**
             * Share Changes
             * @default []
             */
            share_changes: components["schemas"]["ShareChangeResponse"][];
        };
        /**
         * DraftOperationKind
         * @description The three edits the editor offers. Pinning is not among them: it changes no share.
         * @enum {string}
         */
        DraftOperationKind: "add" | "remove" | "bring_back";
        /**
         * DraftOperationRequest
         * @description One edit: what to do, and to which offer.
         */
        DraftOperationRequest: {
            kind: components["schemas"]["DraftOperationKind"];
            /**
             * Offer Id
             * @description The offer, as the tracker numbers it.
             */
            offer_id: number;
        };
        /**
         * EditDraftRequest
         * @description A batch of edits, applied in order and all or nothing.
         */
        EditDraftRequest: {
            /**
             * Operations
             * @description Applied in the order given. One the flow refuses rolls back the whole batch, so a request that answers 409 has changed nothing.
             */
            operations: components["schemas"]["DraftOperationRequest"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportCampaignRequest
         * @description The one number that opens a campaign somebody else built.
         */
        ImportCampaignRequest: {
            /**
             * Keitaro Campaign Id
             * @description The campaign's id in Keitaro, as its URL shows it.
             * @example 93212
             */
            keitaro_campaign_id: number;
        };
        /**
         * InvalidField
         * @description One field a request was refused over, and who refused it.
         *
         *     `location` is dotted from the outside in — `body.country`, `query.limit` — and a
         *     complaint the *tracker* made about a field it was sent is prefixed `tracker.`, so that
         *     one list can carry both without a client having to ask which kind it is holding.
         */
        InvalidField: {
            /** Location */
            location: string;
            /** Message */
            message: string;
        };
        /**
         * LivenessResponse
         * @description Body of `/healthz`.
         */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * OfferCatalogueSyncResponse
         * @description What one press of the refresh did.
         *
         *     `synced_at` is `null` when the tracker listed no offers at all: the local copy was left
         *     exactly as it was, because an empty answer and a failed listing are the same answer from
         *     here and emptying a working catalogue is the worse of the two mistakes.
         */
        OfferCatalogueSyncResponse: {
            /**
             * Offers
             * @description How many offers the tracker listed.
             */
            offers: number;
            /** Synced At */
            synced_at?: string | null;
        };
        /**
         * OfferResponse
         * @description One catalogue offer, in the fields the reference tool's own label is made of.
         *
         *     `11112 Oxys [BEAUTY-CL-BE_0155] [pl es -]` — the id, the name, the network and the
         *     countries, which is every field here and no others.
         *
         *     `country` is a tuple of plain strings and `preview_url` a plain `str`. Both are somebody
         *     else's data: a dash is one of the values Keitaro really keeps in that array, and a
         *     response model that refused to serialise what the tracker sent would turn an offer that
         *     exists into a 500.
         */
        OfferResponse: {
            /** Affiliate Network */
            affiliate_network?: string | null;
            /**
             * Country
             * @default []
             */
            country: string[];
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Preview Url */
            preview_url?: string | null;
            /** State */
            state: string;
        };
        /**
         * OfferShare
         * @description One offer row of a flow, in the three fields the tracker itself keeps.
         */
        OfferShare: {
            /** Offer Id */
            offer_id: number;
            /** Share */
            share: number;
            /** State */
            state: string;
        };
        /**
         * OfferStatsResponse
         * @description What one offer did today — one cell of the editor's Stats column.
         */
        OfferStatsResponse: {
            /**
             * Clicks
             * @default 0
             */
            clicks: number;
            /**
             * Conversions
             * @default 0
             */
            conversions: number;
            /** Offer Id */
            offer_id: number;
        };
        /**
         * OffersResponse
         * @description A page of the combobox. No cursor: the catalogue is searched, not walked.
         */
        OffersResponse: {
            /** Offers */
            offers: components["schemas"]["OfferResponse"][];
        };
        /**
         * PinOfferRequest
         * @description The one number this API takes from a client, and it is still validated server-side.
         */
        PinOfferRequest: {
            /**
             * Share
             * @description Where to hold the row. Omitted means where it is now, which is the button as the screen offers it. Pinning recalculates nothing until the next edit.
             */
            share?: number | null;
        };
        /**
         * ProblemDetails
         * @description A failure, as this API reports one.
         *
         *     Every member the RFC defines that this service fills in, plus the three that carry what
         *     a screen does with a failure: the slug, the id to quote, and the campaign the problem is
         *     about where there is one — which is what lets "already imported" offer to open the
         *     campaign instead of only refusing the request.
         */
        ProblemDetails: {
            /** Campaign Id */
            campaign_id?: string | null;
            /** Code */
            code: string;
            conflict?: components["schemas"]["ConflictingState"] | null;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Detail */
            detail: string;
            /** Errors */
            errors?: components["schemas"]["InvalidField"][] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /**
         * PushDraftRequest
         * @description What the push may do about a flow somebody edited in Keitaro meanwhile.
         */
        PushDraftRequest: {
            /**
             * Overwrite
             * @description Push over changes made in the tracker since this draft was opened. The answer to a 409 and nothing else: overwriting another person's work is a decision.
             * @default false
             */
            overwrite: boolean;
        };
        /**
         * ReadinessResponse
         * @description Body of `/readyz`.
         *
         *     `checks` maps a component name to its verdict and is empty at 1.6, which is the
         *     honest answer: nothing this process depends on exists yet. 5.8 adds
         *     `checks["database"]` and, with it, the 503 branch and the `503` entry in this
         *     operation's OpenAPI responses — all three in one commit, and all before the frontend
         *     generates its types from this schema at 9.6. The shape around `checks` does not move.
         */
        ReadinessResponse: {
            /** Checks */
            checks: {
                [key: string]: "ok" | "error";
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /**
         * ShareChangeResponse
         * @description One offer's share, before and after — the `34 → 33` of the diff summary.
         */
        ShareChangeResponse: {
            /** Now */
            now: number;
            /** Offer Id */
            offer_id: number;
            /** Was */
            was: number;
        };
        /**
         * StreamFilterResponse
         * @description One condition on a flow — `country accept ["AU"]` in the reference campaign.
         */
        StreamFilterResponse: {
            /** Mode */
            mode: string;
            /** Name */
            name: string;
            /**
             * Payload
             * @default []
             */
            payload: string[];
        };
        /**
         * StreamResponse
         * @description One flow: its heading, its rows already ordered, and whether PUSH may be pressed.
         *
         *     `absent` is a flow Keitaro has stopped returning. It is still drawn, because a flow that
         *     vanished from the tracker is something to be told about rather than something to hide.
         */
        StreamResponse: {
            /**
             * Absent
             * @default false
             */
            absent: boolean;
            /** Block Reason */
            block_reason?: string | null;
            /**
             * Can Push
             * @default false
             */
            can_push: boolean;
            diff?: components["schemas"]["DraftDiffResponse"] | null;
            /**
             * Dirty
             * @default false
             */
            dirty: boolean;
            /**
             * Filters
             * @default []
             */
            filters: components["schemas"]["StreamFilterResponse"][];
            /** Keitaro Stream Id */
            keitaro_stream_id: number;
            /** Name */
            name: string;
            /** Position */
            position?: number | null;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["StreamRowResponse"][];
            /**
             * Schema
             * @description `landings` is the only one that rotates offers. Flow 1 is a `redirect`.
             */
            schema: string;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /**
         * StreamRowResponse
         * @description One line of the offer table.
         *
         *     `offer` is `null` for an offer the local catalogue has never heard of, which the screen
         *     draws as `#11234 (not in catalogue)` rather than emptying itself. There is no foreign key
         *     from a flow row to the catalogue and there is not meant to be.
         */
        StreamRowResponse: {
            offer?: components["schemas"]["OfferResponse"] | null;
            /** Offer Id */
            offer_id: number;
            /** Pinned Share */
            pinned_share?: number | null;
            /**
             * Removed
             * @default false
             */
            removed: boolean;
            /** Share */
            share: number;
        };
        /**
         * StreamStatsResponse
         * @description What one flow took today — the number the editor prints in the group heading.
         */
        StreamStatsResponse: {
            /**
             * Clicks
             * @default 0
             */
            clicks: number;
            /** Keitaro Stream Id */
            keitaro_stream_id: number;
        };
        /**
         * StreamsResponse
         * @description The whole editor screen: the campaign in the toolbar, and its flows below it.
         */
        StreamsResponse: {
            campaign: components["schemas"]["CampaignResponse"];
            /** Streams */
            streams: components["schemas"]["StreamResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_campaigns_api_v1_campaigns_get: {
        parameters: {
            query?: {
                /** @description Free text over the name and the alias. */
                q?: string | null;
                limit?: number;
                /** @description The `next_cursor` of the page before this one. */
                after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignsPageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    create_campaign_api_v1_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    import_campaign_api_v1_campaigns_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportCampaignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    refetch_campaign_api_v1_campaigns__campaign_id__refetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    repair_campaign_api_v1_campaigns__campaign_id__repair_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    read_campaign_stats_api_v1_campaigns__campaign_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignStatsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_streams_api_v1_campaigns__campaign_id__streams_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_draft_api_v1_campaigns__campaign_id__streams__stream_id__draft_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                stream_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_draft_api_v1_campaigns__campaign_id__streams__stream_id__draft_operations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                stream_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    preview_draft_api_v1_campaigns__campaign_id__streams__stream_id__draft_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                stream_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_draft_api_v1_campaigns__campaign_id__streams__stream_id__draft_push_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                stream_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    pin_offer_api_v1_campaigns__campaign_id__streams__stream_id__offers__offer_id__pin_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                stream_id: number;
                offer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinOfferRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    unpin_offer_api_v1_campaigns__campaign_id__streams__stream_id__offers__offer_id__pin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                stream_id: number;
                offer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_offers_api_v1_offers_get: {
        parameters: {
            query?: {
                /** @description Matched against the offer id as a prefix, and the name. */
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OffersResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    sync_offers_api_v1_offers_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferCatalogueSyncResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
