"""The mirror of one campaign: campaigns, streams, stream_offers, offer_pins.

Autogenerated and then read. The three foreign keys are ON DELETE RESTRICT and nothing
cascades: a row the tracker stopped returning becomes a tombstone, never a DELETE.

Revision ID: 0001
Create Date: 2026-09-20
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None

MIRROR_STATE = sa.Enum(
    "present", "absent", name="mirror_state", native_enum=False, create_constraint=True, length=8
)
SETUP_STATUS = sa.Enum(
    "ready",
    "needs_attention",
    name="setup_status",
    native_enum=False,
    create_constraint=True,
    length=16,
)
TOMBSTONE_IS_DATED = "(mirror_state = 'absent') = (absent_since IS NOT NULL)"


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("keitaro_campaign_id", sa.BigInteger(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("setup_status", SETUP_STATUS, server_default=sa.text("'ready'"), nullable=False),
        sa.Column("public_domain", sa.Text(), nullable=True),
        sa.Column("requested_country", sa.Text(), nullable=True),
        sa.Column("requested_offer_id", sa.BigInteger(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("keitaro_campaign_id", name=op.f("uq_campaigns_keitaro_campaign_id")),
    )
    op.create_index(
        op.f("ix_campaigns_created_at_id"), "campaigns", ["created_at", "id"], unique=False
    )
    op.create_table(
        "streams",
        # autoincrement=False, or the column is BIGSERIAL and Postgres attaches a sequence
        # to an id only the tracker assigns.
        sa.Column("keitaro_stream_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("schema", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "mirror_state", MIRROR_STATE, server_default=sa.text("'present'"), nullable=False
        ),
        sa.Column("absent_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            TOMBSTONE_IS_DATED, name=op.f("ck_streams_absent_since_matches_mirror_state")
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_streams_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("keitaro_stream_id", name=op.f("pk_streams")),
    )
    op.create_index(
        op.f("ix_streams_campaign_id_position"),
        "streams",
        ["campaign_id", "position"],
        unique=False,
    )
    op.create_table(
        "stream_offers",
        sa.Column("stream_id", sa.BigInteger(), nullable=False),
        # No foreign key to offers.id: an offer can reach a flow before our catalogue has it.
        sa.Column("offer_id", sa.BigInteger(), nullable=False),
        # No CHECK on share in either direction: a clean stream in the tracker sums to 50.
        sa.Column("share", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("keitaro_row_id", sa.BigInteger(), nullable=True),
        sa.Column("keitaro_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "mirror_state", MIRROR_STATE, server_default=sa.text("'present'"), nullable=False
        ),
        sa.Column("absent_since", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            TOMBSTONE_IS_DATED, name=op.f("ck_stream_offers_absent_since_matches_mirror_state")
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["streams.keitaro_stream_id"],
            name=op.f("fk_stream_offers_stream_id_streams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("stream_id", "offer_id", name=op.f("pk_stream_offers")),
    )
    op.create_table(
        "offer_pins",
        sa.Column("stream_id", sa.BigInteger(), nullable=False),
        sa.Column("offer_id", sa.BigInteger(), nullable=False),
        sa.Column("locked_share", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Ours, so checked — the deliberate opposite of stream_offers.share above.
        sa.CheckConstraint(
            "locked_share BETWEEN 0 AND 100",
            name=op.f("ck_offer_pins_locked_share_is_a_percentage"),
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["streams.keitaro_stream_id"],
            name=op.f("fk_offer_pins_stream_id_streams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("stream_id", "offer_id", name=op.f("pk_offer_pins")),
    )


def downgrade() -> None:
    """Revert this revision."""
    op.drop_table("offer_pins")
    op.drop_table("stream_offers")
    op.drop_index(op.f("ix_streams_campaign_id_position"), table_name="streams")
    op.drop_table("streams")
    op.drop_index(op.f("ix_campaigns_created_at_id"), table_name="campaigns")
    op.drop_table("campaigns")
